export const routes = {
  home: "/",
  auth: "/auth",
  loginIn: "/login",
  signUp: "/signup",
  forgotPassword: "/forgotPassword",
  propertyDetails: "/property/:id",
  properties: "/properties",
  propertiesSearch: "/properties/search",
  propertiesMap: "/properties/map",
  favourites: "/favourites",
  account: "/account",
  error: "*",
  profile: "/profile",
};
